### Variáveis
@url=http://localhost:3000


### Contatos
GET {{url}}/api/contatos

### 
GET {{url}}/api/contatos/d8c8091c-9e08-45d0-93a9-5b7e65402062


### Requisição POST
POST {{url}}/api/contatos
Content-Type: application/json

{
    "nome":"renata",
    "email": "renata123@gmail.com",
    "telefone": "44234561234"
}

### Requisição PUT
PUT {{url}}/api/contatos/d8c8091c-9e08-45d0-93a9-5b7e65402062
Content-Type: application/json

{    
    "nome":"Josefina Silva",
    "email": "josefina-silva@gmail.com",
    "telefone": "44123451234"
}

### Requisição DELETE
DELETE {{url}}/api/contatos/d8c8091c-9e08-45d0-93a9-5b7e65402062